default:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/maven:3-openjdk-17
  tags:
    - docker

stages:
  - compile
  - test
  - post_process
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  SONAR_USER_HOME: "$CI_PROJECT_DIR/.sonar"

cache:
  paths:
    - .m2/repository
    - .sonar

compile_source:
  stage: compile
  script:
    - mvn clean process-classes -U
  artifacts:
    name: compiled_sources
    expire_in: 1 hour
    paths:
      - target/*

compile_test:
  stage: compile
  script:
    - mvn process-test-classes
  needs:
    - compile_source
  artifacts:
    name: compiled_sources_and_tests
    expire_in: 1 hour
    paths:
      - target/*

.test_job:
  stage: test
  needs:
    - compile_test

test_unit:
  extends: .test_job
  script:
    - mvn package
  artifacts:
    name: unit_artifacts
    reports:
      junit:
        - "target/surefire-reports/TEST-*.xml"
    expire_in: 1 hour
    paths:
      - target/jacoco.exec
      - "target/surefire-reports/TEST-*.xml"

test_integration:
  extends: .test_job
  script:
    - mvn install -Dsurefire.skip
  artifacts:
    name: integration_artifacts
    reports:
      junit:
        - "target/failsafe-reports/TEST-*.xml"
    expire_in: 1 hour
    paths:
      - "target/failsafe-reports/TEST-*.xml"

.post-processing_job:
  stage: post_process
  allow_failure: true

maven_site:
  extends: .post-processing_job
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - mvn site
    - grep -Po "Total.*?([0-9]{1,3})%" target/site/jacoco/index.html
  needs:
    - compile_test
    - test_unit
    - test_integration
  artifacts:
    name: site_artifacts
    expire_in: 1 hour
    paths:
      - target/site

visualize_coverage:
  extends: .post-processing_job
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
  needs:
    - maven_site
  artifacts:
    reports:
      cobertura: target/site/cobertura.xml

sonarqube:
  extends: .post-processing_job
  when: always
  needs:
    - test_unit
    - test_integration
    - compile_test
    - maven_site
  script:
    - mvn sonar:sonar -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_TOKEN -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY -Dsonar.projectName="$SONARQUBE_PROJECT_NAME"

pages:
  stage: deploy
  allow_failure: true
  only:
    - master
  script:
    - mkdir public
    - mv target/site public
  needs:
    - maven_site
  artifacts:
    name: page_artifacts
    expire_in: 1 hour
    paths:
      - public

.deploy_job:
  stage: deploy
  allow_failure: true
  only:
    - master
  needs:
    - compile_source
    - compile_test
    - test_unit
    - test_integration

deploy_maven_package:
  extends: .deploy_job
  script:
    - mvn deploy -s ci_settings.xml -Dsurefire.skip -Dfailsafe.skip

deploy_jib_image:
  extends: .deploy_job
  script:
    - mvn -s ci_settings.xml jib:build
